### ISSUE TITLE
Add compability for RollTheDice Plugin

### ISSUE THREAD

**Issue by WOLFA22** [sapphonie/StAC-tf2#11]
Effects associated with viewing angles antichit sees as a detector and bans legitimate players. Please make it compatible with RollTheDice plugins.

Used plugin from here: https://forums.alliedmods.net/showthread.php?t=278579

**Comment by sapphonie** [comment]
set `stac_max_fakeang_detections` to `-1` (disable completely) or `0` (show detections but don't disable)

stac is not particularly meant to be used with "silly plugins" like rtd or 3rd person plugins etc
