### ISSUE TITLE
Stac causes processing time exceeded 

### ISSUE THREAD

**Issue by higps** [sapphonie/StAC-tf2#133]
When I updated to the latest stac, whenever I switch robots in my robot mode, it causes the error mentioned above.

**Comment by alekny** [comment]
It's probably because you use "stac_optimize_cvars 1", as it sets "net_chan_limit_msec 75". Try "stac_optimize_cvars 0" in your config and check again.
The same thing happens if you execute etf2l configs on match servers btw.

**Comment by sapphonie** [comment]
If you change net_chan_limit_msec to a higher number stac will respect that value. I would try 100 or 150. Raise it until people no longer get kicked

**Comment by sapphonie** [comment]
> 



> It's probably because you use "stac_optimize_cvars 1", as it sets "net_chan_limit_msec 75". Try "stac_optimize_cvars 0" in your config and check again. The same thing happens if you execute etf2l configs on match servers btw.

This is fixable by ETF2L or that specific server owner setting net_chan_limit_msec to a higher value in their configs. I highly recommend *not* disabling stac_optimize_cvars since it patches a bunch of cheat features
