### ISSUE TITLE
Auto-updated STAC wants SM 1.12 after reloading

### ISSUE THREAD

**Issue by Dragonisser** [sapphonie/StAC-tf2#164]
Update from 6.0.4 to 6.0.5
SourceMod Version: 1.11.0.6924

Was only fixed via manually downloading the latest version of the plugin and installing it.

sm plugins reload stac
[SM] Plugin stac.smx failed to reload: Newer SourceMod required (1.12.0.7041 or higher).
[SM] Plugin stac.smx reloaded successfully.

Even a server restart doesnt seem to fix it. Can reproduce it 100%

**Comment by sapphonie** [comment]
Issue with my locally (wrong version) compiled version getting pushed to the repo for autoupdater. Whoops. Will fix in a bit. Probably will require everyone to reinstall from repo

**Comment by sapphonie** [comment]
ca3eac8dd509e2bc19832a7524501f6388b413c8 - if you're getting this issue you have to reinstall from the latest release version
