### ISSUE TITLE
net_chan_limit_msec 

### ISSUE THREAD

**Issue by Fate970730** [sapphonie/StAC-tf2#183]
Due to the setting of `net_chan_limit_msec`, my teammates and I get processing time exceeded when they just enter commands such as `/taunt /slghost /admin` etc. in the chat, could this be somehow prevented from happening?

**Comment by sapphonie** [comment]
stac won't override `net_chan_limit_msec` so long as set it to something that isn't `0`. try starting at 256 and going up from there until it stops kicking legit players

**Comment by Fate970730** [comment]
like, for example, should I enter this in server.cfg?
sm_cvar net_chan_limit_msec "256"

**Comment by sapphonie** [comment]
> like, for example, should I enter this in server.cfg? `sm_cvar net_chan_limit_msec "256"`

Yes
