### ISSUE TITLE
"STEAM validation rejected" error after x64 update

### ISSUE THREAD

**Issue by aarmastah** [sapphonie/StAC-tf2#193]
After yesterday's first update, when StAC is installed on a TF2 server and run (using the 32-bit executable), it results in the error message "STEAM validation rejected" shown to all clients:

![image](https://github.com/sapphonie/StAC-tf2/assets/1887380/7ff5044c-304e-4f49-9ba2-aaf9795d81fe)

(Tested using Ubuntu Server 22.04)

I tried reinstalling plugins on a clean SourceMod install one by one to isolate this issue to StAC. Additionally, nothing shows up in my server console when players attempt to join and receive this error. Let me know if anything else is needed for debugging/troubleshooting and I'll do my best to help.

**Comment by alekny** [comment]
Same issue here, the problem seems to be related to the "connect" extension. Since stac requires it, the only "workaround" for now is to disable it.

**Comment by aarmastah** [comment]
Here's the issue from the Connect extension: https://github.com/asherkin/connect/issues/19

Seems like there's not much to be done on the StAC side right now (maybe at all). Hoping an update to Connect fixes it 🤞

**Comment by llamasking** [comment]
StAC could temporarily remove the Connect extension, but that does mean the validation it does is removed as well. Sub-optimal, but a stop-gap that might be worth considering if Connect takes too long to fix.

I personally managed to get past the message with a simple recompile of Connect, but I also am not entirely sure if it is doing what it's supposed to or was simply broken by doing that.

**Comment by Dragonisser** [comment]
The other possibility is to downgrade to StAC v5.4.3 which doesn't use connect yet. Not ideal either, but better than nothing. 

https://github.com/sapphonie/StAC-tf2/releases/tag/v5.4.3

**Comment by sapphonie** [comment]
Connect is being actively worked on by other members of the community and I have merge access to the repository, it will be ready when it is ready, just be patient please!

**Comment by sapphonie** [comment]
#195 / v6.1.5
