### ISSUE TITLE
[Issue] connect.ext

### ISSUE THREAD

**Issue by CodaCM** [sapphonie/StAC-tf2#194]
when I try to run StAC,
I get this error 
[SM] Plugin stac.smx failed to reload: Required extension "Connect" file("connect.ext") not running.
could it just be because of the x64 update or is SM just broken in general after the update?

**Comment by sapphonie** [comment]
https://github.com/sapphonie/StAC-tf2/issues/193#issuecomment-2067767784

**Comment by sapphonie** [comment]
https://github.com/sapphonie/StAC-tf2/pull/195 / v6.1.5
