### ISSUE TITLE
Server Crash after installing addon

### ISSUE THREAD

**Issue by KhalDrogo1988** [sapphonie/StAC-tf2#197]
Hi, My server crashing after installing Your addon https://crash.limetech.org/cwemnldnq5p3  any help ? Installed latest v6.1.5

**Comment by sapphonie** [comment]
More info required:

Need the output from these commands in server console, preferably in a pastebin or something similar:

`version; plugin_print; meta version; meta list; sm version; sm exts list; sm plugins list`

Ty

**Comment by sapphonie** [comment]
Actually, uninstall `cbaseserver.ext.2.ep2v.so`, which is outdated, crusty, and there is 0 reason to use in the modern day

**Comment by KhalDrogo1988** [comment]
Hmmm , looks like after deleting cbaseserver.ext.2.ep2v.so now all work ok no crashes. I gonna close issue, if still problem gonna persist I will reopen . Thx anyway :)
