### ISSUE TITLE
Pre-Fortress 2 compatibility

### ISSUE THREAD

**Issue by blackletum** [sapphonie/StAC-tf2#200]
Tried to add this sourcemod to PF2, when compiling I get the following:

Compiling stac.sp...
SourcePawn Compiler 1.11.0.6916
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

stac/stac_stocks.sp(769) : error 017: undefined symbol "Discord_EscapeString"
stac/stac_stocks.sp(1236) : error 017: undefined symbol "Discord_SendMessage"

2 Errors.

**Comment by alekny** [comment]
Did you make sure "discord.inc" is in your scripts/include folder? Stac needs all of those to compile: https://github.com/sapphonie/StAC-tf2/tree/master/scripting/include
