### ISSUE TITLE
warioware + stac = everyone gets banned

### ISSUE THREAD

**Issue by gdfsgdfg** [sapphonie/StAC-tf2#209]
I decided to run this plugin thinking nothing will go wrong until I changed the game mode to this one https://github.com/gemidyne/microtf2

Could also be because of the host_timescale_fix one but who knows.

It was a funny moment when me and the others who were on got banned from stac never the less that made me toss this plugin aside lol.

Windows Server if that makes any difference.

So yeah don't pair up these two.

**Comment by sapphonie** [comment]
StAC was never designed for "silly" modes, like warioware, trade servers, jailbreak, etc, and at this point I should probably have a FAQ for this plugin that includes that info. 

In the mean time, this is a terrible bug report, if you're going to report an issue please at least be specific about exactly what is going on on your server e.g. by running `version; plugin_print; meta version; meta list; sm version; sm exts list; sm plugins list` in server console and posting output, as well as posting your stac_log and what stac says they even got banned for. You can't just be like "this plugin broken :(" and expect me to do anything about it with no info, come on lol

It's entirely possible I can easily fix this in the plugin itself, but I will need more info from you. Thanks!

**Comment by gdfsgdfg** [comment]
Well I had no idea it created logs but it basically seems like it detected us as using sv_cheats commands.

[StAC] [Detection] Player Yellow Dice is cheating - OOB cvar/netvar value 1 on var sv_cheats!

Would it do the same if in theory like a plugin let you use cheats locked commands as an admin.

I think jailbreak and trade servers should be fine but I guess it comes down to what plugins you're using.
