### ISSUE TITLE
russian / danish translations incorrect with 5.0.0

### ISSUE THREAD

**Issue by sapphonie** [sapphonie/StAC-tf2#32]
@Blueberryy @ksgoescoding - your translations for this plugin are greatly appreciated, however, stac has recieved numerous updates since you contributed them. if you could update them based off of v5.0.0, it would be much appreciated. if not, i'm gonna go ahead and remove them for now.

**Comment by ksgoescoding** [comment]
@sapphonie 

I have not made a pull-request with the updated translation.

**Comment by Blueberryy** [comment]
@sapphonie here we go #35
