### ISSUE TITLE
Third Person plugin is not work

### ISSUE THREAD

**Issue by gaejuck** [sapphonie/StAC-tf2#41]
First of all, thank you for being able to prevent bad users thanks to StAC.
But after adding the StAC, If I try third peron with third person plugin, will be return to first person in a few minutes.
I used this plugin https://forums.alliedmods.net/showthread.php?p=2028480
How can I fix it?

**Comment by sapphonie** [comment]
I can remove the `firstperson` command that gets sent to clients in the next stac update, as it is not very useful and a remnant of when this plugin was more focused on patching cheats than banning people for cheating

**Comment by sapphonie** [comment]
fixed in #44 aka version 5.0.7

**Comment by gaejuck** [comment]
Thank you so much for being fixed!
