### ISSUE TITLE
False choke detections 

### ISSUE THREAD

**Issue by JONTTM** [sapphonie/StAC-tf2#42]
![image](https://user-images.githubusercontent.com/14990787/122352757-1b902500-ceeb-11eb-92dd-5032ab29dfa3.png)
A mod of mine reported this today (shortly after we implemented StAC on the servers). 

Quote:
> It's called me several times for having choke hacks or whatever (i have 79 ping currently connected to SF)

**Comment by sapphonie** [comment]
That check is bunk, or more accurately, it is still in beta. I do not know how it snuck on to master but I will remove it
