### ISSUE TITLE
MaterialAdmin Support

### ISSUE THREAD

**Issue by MAGNAT2645** [sapphonie/StAC-tf2#54]
Would be good to have support for [MaterialAdmin](https://github.com/SB-MaterialAdmin/NewServer).

**Comment by sapphonie** [comment]
I can't read russian, do I just need the inc file?

**Comment by MAGNAT2645** [comment]
Sure. Include file has russian and english description.

**Comment by MAGNAT2645** [comment]
I think this can be closed now.
