### ISSUE TITLE
pipes.cpp Bug and perfomance major bug var x2

### ISSUE THREAD

**Issue by jaid76** [sapphonie/StAC-tf2#59]
src/common/pipes.cpp (560) : Assertion Failed: m_OutstandingCallbackThreadId != ThreadGetCurrentId()
src/common/pipes.cpp (560) : Assertion Failed: m_OutstandingCallbackThreadId != ThreadGetCurrentId()
src/common/pipes.cpp (560) : Assertion Failed: m_OutstandingCallbackThreadId != ThreadGetCurrentId()
src/common/pipes.cpp (560) : Assertion Failed: m_OutstandingCallbackThreadId != ThreadGetCurrentId()

n+ spam every tick at empty server

 @sapphonie

**Comment by jaid76** [comment]
Prob can be fixed by this version steamtools https://builds.limetech.io/files/steamtools-0.10.0-git179-54fdc51-linux.zip

**Comment by sapphonie** [comment]
this isn't a bug with stac, unless i'm missing something...?
