### ISSUE TITLE
Triggerbot detection false positives when using mice with 2ms debouce (de-click)

### ISSUE THREAD

**Issue by crich10** [sapphonie/StAC-tf2#79]
A regular in our community found that the Triggerbot was printing false positives when he was "slamming" his mouse down on the mousepad. I use quotes on slamming because he wasn't rage smashing the mouse -- it was when he would pick his mouse up to adjust for running out of mousepad.

His description of the mouse used to test:
"im using a mouse with 1000hz polling rate and 2ms debounce time, which is practically instantaneous response rate".

His working theory on the problem:
craig: its because the mouse's clicks are controlled by mechanical switches that are very easy to activate, hence why the response time is so fast. But because the response time is so quick and the switches are so light, if i slam my mouse on the desk it thinks im using triggerbot because the response rate is just that fast.

He also created a video to demonstrate the issue. The video shows him tapping the mouse against his desk repeatably, which you'd never do in a game obviously, but the issue can be consistently re-created in-context (one tap can still trigger it like when you're picking the mouse up to adjust for no more mousepad).

Video: https://www.youtube.com/watch?v=K8aXs-m3j0E
Link to mouse used to test: https://www.pcgamingrace.com/products/glorious-model-o-wireless-matte-black

**Comment by sapphonie** [comment]
Is this only triggerbot?

**Comment by crich10** [comment]
For this particular issue yes.

We have had other false positives from triggerbot and silentaim, but we never spent time to hunt down the actual cause like we did here. Will investigate further whenever it pops up again and reach out if I think its a seperate issue.

**Comment by sapphonie** [comment]
Interesting, I'll see what I can do. Thank you for the report.

**Comment by sapphonie** [comment]
closed in #77
